
import { AssetStatus, CryptographicAsset } from './types';

export const MOCK_ASSETS: CryptographicAsset[] = [
  {
    id: 'asset-001',
    name: 'Primary TLS Certificate',
    type: 'Certificate',
    algorithm: 'RSA-2048',
    status: AssetStatus.VULNERABLE,
    associatedSystems: ['Web Server Cluster A', 'API Gateway'],
    lastAuditDate: '2023-10-15',
    migrationPlanStatus: 'Planning Phase',
  },
  {
    id: 'asset-002',
    name: 'VPN Server Key',
    type: 'Key',
    algorithm: 'ECDSA P-256',
    status: AssetStatus.VULNERABLE,
    associatedSystems: ['Corporate VPN Concentrator'],
    lastAuditDate: '2023-11-01',
    migrationPlanStatus: 'Not Started',
  },
  {
    id: 'asset-003',
    name: 'Database Encryption Key',
    type: 'Key',
    algorithm: 'Kyber-512',
    status: AssetStatus.PQC_READY,
    associatedSystems: ['PostgreSQL DB Cluster'],
    lastAuditDate: '2024-03-20',
    migrationPlanStatus: 'Completed',
  },
  {
    id: 'asset-004',
    name: 'Code Signing Certificate',
    type: 'Certificate',
    algorithm: 'Dilithium2',
    status: AssetStatus.PQC_READY,
    associatedSystems: ['CI/CD Pipeline'],
    lastAuditDate: '2024-02-10',
    migrationPlanStatus: 'Completed',
  },
  {
    id: 'asset-005',
    name: 'Internal CA Certificate',
    type: 'Certificate',
    algorithm: 'RSA-4096',
    status: AssetStatus.IN_PROGRESS,
    associatedSystems: ['Internal PKI'],
    lastAuditDate: '2024-01-05',
    migrationPlanStatus: 'Migration in Progress',
  },
  {
    id: 'asset-006',
    name: 'SSH Server Key - Prod',
    type: 'Key',
    algorithm: 'Ed25519',
    status: AssetStatus.NOT_STARTED,
    associatedSystems: ['Production Server Fleet'],
    lastAuditDate: '2023-12-18',
    migrationPlanStatus: 'Awaiting Vendor Patch',
  },
    {
    id: 'asset-007',
    name: 'JWT Signing Key',
    type: 'Key',
    algorithm: 'ECDSA P-384',
    status: AssetStatus.VULNERABLE,
    associatedSystems: ['Authentication Service'],
    lastAuditDate: '2024-02-28',
    migrationPlanStatus: 'Researching Alternatives',
  },
  {
    id: 'asset-008',
    name: 'Backup Encryption Token',
    type: 'Key',
    algorithm: 'Falcon-512',
    status: AssetStatus.IN_PROGRESS,
    associatedSystems: ['Cloud Backup Solution'],
    lastAuditDate: '2024-03-11',
    migrationPlanStatus: 'Testing Phase',
  },
];
